version: '3'

networks:
  backend:

volumes:
  produtosdata:

services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: okayfine
      POSTGRES_DB: falcon
    networks:
        - backend

  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - backend
    ports:
      - "7284:443"
      - "7283:80"
    environment:
      ConnectionStrings__Default: "Host=db;Port=5432;Database=falcon;Username=postgres;Password=okayfine;"
    depends_on:
      - db